name: Master Pipeline

on:
  # Triggers the workflow on 'push' events to the 'main' branch.
  # This means every time code is pushed directly to 'main' (or a PR is merged into 'main').
  push:
    branches: [ main ]

  # Triggers the workflow on 'pull_request' events targeting the 'main' branch.
  # This is crucial for pre-merge checks, ensuring code quality before integration.
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

# Check and add permissions that is required by nested workflow
permissions:
  packages: write
  contents: read
  pages: write 
  id-token: write

# Chaining the different workflow
jobs:   
  call-ci:
    uses: ./.github/workflows/ci.yaml
    
  call-cd-build-image:
    if: github.event_name == 'push'
    needs: call-ci
    uses: ./.github/workflows/cd_build_image.yaml
    
  call-cd-deploy:
    if: github.event_name == 'push'
    needs: call-cd-build-image
    uses: ./.github/workflows/cd_deploy.yaml